wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725675152
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.17.9
      6: ''
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
